spring:
  application:
    name: itshop-user

server:
  port: 1202

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka/

security:
  oauth2:
    resource:
      id: itshop-user
      user-info-uri: http://localhost:1302/auth/api/user
      prefer-token-info: false
      user:
        name:
        password: